### ISSUE TITLE
No error shows up when uploading large size CSV files

### ISSUE THREAD

**Issue by daniellegayares** [thinkingmachines/linksight#197]
Using csv file with more than 3k rows: 

Upload freezes on csv with >3k rows, no error shows up

![image](https://user-images.githubusercontent.com/33336908/45468240-3d668700-b756-11e8-920b-e11a98167f6b.png)

![image](https://user-images.githubusercontent.com/33336908/45468729-c4b4fa00-b758-11e8-8304-1789dd94802d.png)

When cut into 4k, works properly

![image](https://user-images.githubusercontent.com/33336908/45470526-af43ce00-b760-11e8-8e9f-1fedcb7f759f.png)

**Comment by marksteve** [comment]
@syk0saje @daniellegayares  This happens because of nginx. And since nginx throws the error, it's not a valid json response w/c is what filepond is expecting (because of the error handler I added). Filepond is most probably encountering this as an error and since it's within the error handler, it just gets stuck.

**Comment by syk0saje** [comment]
@marksteve what do you think of using this to set a client-side limit: https://github.com/pqina/filepond-plugin-file-validate-size

we just have to make sure it's equal to or smaller than the limit on nginx
