### ISSUE TITLE
Add accuracy profiling system to tests

### ISSUE THREAD

**Issue by syk0saje** [thinkingmachines/linksight#234]
reference: https://docs.google.com/spreadsheets/d/18Bf3YmhYdbtduYTA8KOS9MLhDs8AcMBmbaHfx84k-U4/edit#gid=147027782

summary should include the following:
- accuracy [%] (how close is the right result to the top?)
  - [x] required
  - [ ] optional

**Comment by syk0saje** [comment]
Blocking on #233

**Comment by syk0saje** [comment]
#233 has been closed, can proceed

**Comment by florobarotjr** [comment]
Just to document, we have tests for the edge cases and for exact matches. The test for the 2000 records with messy data is the one that is disabled due to how slow it runs (2 minutes per run)

As of the moment, the `get_accuracy` function only caters to exact matches (by counting the number of exact matches).

Needed adjustments:
- better accuracy check. I'll change to make use of the `expected` columns
- figure out how to check accuracy of messy data. We probably need the 'I feel lucky' flag of the matcher and use that to check. Another option is to just check if the `expected` field is in the list of possible answers
