### ISSUE TITLE
Nothing happens after I export CSV

### ISSUE THREAD

**Issue by piafaustino** [thinkingmachines/linksight#48]
After running through the whole matching process on the family doc CSV, I hit "export" and end up on this blank page without an exported CSV

https://linksight.thinkingmachin.es/media/datasets/FamilyDOC_Branches_-_Sheet1-matched_92OLLPQ.csv

**Comment by marksteve** [comment]
Turns out it was the service worker causing this. The service worker allows the app to be loaded even when there's not internet. Not completely sure about the mechanism on how assets are loaded from the cache by service workers but removing it's registration fixed the issue.

@piafaustino You might need to clear your storage for this to work:
1. <kbd>Command</kbd> + <kbd>Shift</kbd> + <kbd>J</kbd>
1. Click on the Application tab
1. Select `Clear storage` from the left sidebar
1. Make sure `Unregister service workers` is selected then click `Clear site data` at the bottom

**Comment by piafaustino** [comment]
@marksteve Command Shift J made my download tab appear. Weird! Can I check this with you later

**Comment by piafaustino** [comment]
Resolved

**Comment by daniellegayares** [comment]
Happened to me! What can be done in the backend so that people who access the site more than once won't encounter problem.

Windows solution: Right Click, Inspect, Application Tab, Clear Site Data.
